In [ ]:
import pandas as pd

df = pd.read_csv("ecommerce_behavior_data.csv")

df.head()

,user_id,event_time,event_type,product_id,product_name,category,price,device,country
0,U00001,2023-01-01 04:18:26,view,P1024,Nike dress,clothing,763.35,mobile,UK
1,U00001,2023-01-01 04:22:26,view,P1058,Nike lipstick,beauty,910.18,tablet,India
2,U00001,2023-01-01 04:26:26,view,P1068,Adidas serum,beauty,729.15,desktop,USA
3,U00001,2023-02-01 04:47:32,view,P1041,Puma lamp,home,920.41,desktop,UK
4,U00001,2023-02-01 04:51:32,view,P1030,Nike shoes,clothing,330.99,mobile,UK

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 206726 entries, 0 to 206725
Data columns (total 9 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   user_id       206726 non-null  object
 1   event_time    206726 non-null  object
 2   event_type    206726 non-null  object
 3   product_id    206726 non-null  object
 4   product_name  206726 non-null  object
 5   category      206726 non-null  object
 6   price         206726 non-null  float64
 7   device        206726 non-null  object
 8   country       206726 non-null  object
dtypes: float64(1), object(8)
memory usage: 14.2+ MB

In [ ]:
funnel = df.groupby('event_type')['user_id'].nunique()
print(funnel)

event_type
cart        4986
purchase    4355
view        5000
Name: user_id, dtype: int64

In [ ]:
views = df[df['event_type']=='view']['user_id'].nunique()
purchases = df[df['event_type']=='purchase']['user_id'].nunique()

conversion_rate = (purchases / views) * 100
print("Conversion Rate:", round(conversion_rate,2), "%")

Conversion Rate: 87.1 %

In [ ]:
df['event_time'] = pd.to_datetime(df['event_time'])
df['date'] = df['event_time'].dt.date

In [ ]:
daily_users = df.groupby('date')['user_id'].nunique()
daily_users.head()

date
2023-01-01    136
2023-01-02    141
2023-01-03    133
2023-01-04    129
2023-01-05    141
Name: user_id, dtype: int64

In [ ]:
dates = sorted(df['date'].unique())

day1_users = set(df[df['date'] == dates[0]]['user_id'])
day2_users = set(df[df['date'] == dates[1]]['user_id'])

retention_rate = len(day1_users & day2_users) / len(day1_users) * 100

print("Day 1 to Day 2 Retention:", round(retention_rate,2), "%")

Day 1 to Day 2 Retention: 5.15 %